// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.Stronghold2016;

// BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.CounterBase.EncodingType;
import edu.wpi.first.wpilibj.DigitalInput;
import edu.wpi.first.wpilibj.Encoder;
import edu.wpi.first.wpilibj.PIDSourceType;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.Talon;
import edu.wpi.first.wpilibj.VictorSP;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=IMPORTS
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 * The RobotMap is a mapping from the ports sensors and actuators are wired into
 * to a variable name. This provides flexibility changing wiring, makes checking
 * the wiring easier and significantly reduces the number of magic numbers
 * floating around.
 */
public class RobotMap {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    public static SpeedController driveTrainLeftMotor;
    public static SpeedController driveTrainRightMotor;
    public static RobotDrive driveTrainRobotDrive21;
    public static Encoder driveTrainLeftMotorEncoder;
    public static Encoder driveTrainRightMotorEncoder;
    public static SpeedController shooterRightMotor;
    public static SpeedController shooterLeftMotor;
    public static DigitalInput feederballReady;
    public static SpeedController feederRoller;
    public static SpeedController feederLimboBar;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    public static void init() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
        driveTrainLeftMotor = new VictorSP(0);
        LiveWindow.addActuator("DriveTrain", "LeftMotor", (VictorSP) driveTrainLeftMotor);
        
        driveTrainRightMotor = new VictorSP(1);
        LiveWindow.addActuator("DriveTrain", "RightMotor", (VictorSP) driveTrainRightMotor);
        
        driveTrainRobotDrive21 = new RobotDrive(driveTrainLeftMotor, driveTrainRightMotor);
        
        driveTrainRobotDrive21.setSafetyEnabled(true);
        driveTrainRobotDrive21.setExpiration(0.1);
        driveTrainRobotDrive21.setSensitivity(0.5);
        driveTrainRobotDrive21.setMaxOutput(1.0);

        driveTrainRobotDrive21.setInvertedMotor(RobotDrive.MotorType.kRearRight, true);
        driveTrainLeftMotorEncoder = new Encoder(0, 1, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "LeftMotorEncoder", driveTrainLeftMotorEncoder);
        driveTrainLeftMotorEncoder.setDistancePerPulse(1.0);
        driveTrainLeftMotorEncoder.setPIDSourceType(PIDSourceType.kDisplacement);
        driveTrainRightMotorEncoder = new Encoder(2, 3, false, EncodingType.k4X);
        LiveWindow.addSensor("DriveTrain", "RightMotorEncoder", driveTrainRightMotorEncoder);
        driveTrainRightMotorEncoder.setDistancePerPulse(1.0);
        driveTrainRightMotorEncoder.setPIDSourceType(PIDSourceType.kDisplacement);
        shooterRightMotor = new VictorSP(3);
        LiveWindow.addActuator("Shooter", "Right Motor", (VictorSP) shooterRightMotor);
        
        shooterLeftMotor = new VictorSP(2);
        LiveWindow.addActuator("Shooter", "Left Motor", (VictorSP) shooterLeftMotor);
        
        feederballReady = new DigitalInput(4);
        LiveWindow.addSensor("Feeder", "ball Ready", feederballReady);
        
        feederRoller = new Talon(4);
        LiveWindow.addActuator("Feeder", "Roller", (Talon) feederRoller);
        
        feederLimboBar = new Talon(5);
        LiveWindow.addActuator("Feeder", "Limbo Bar", (Talon) feederLimboBar);
        

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTORS
    }
}
