// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.


package org.usfirst.frc1735.Stronghold2016.subsystems;

import org.usfirst.frc1735.Stronghold2016.Robot;
import org.usfirst.frc1735.Stronghold2016.RobotMap;
import org.usfirst.frc1735.Stronghold2016.commands.*;
import edu.wpi.first.wpilibj.AnalogPotentiometer;
import edu.wpi.first.wpilibj.PIDController;
import edu.wpi.first.wpilibj.RobotDrive;
import edu.wpi.first.wpilibj.SpeedController;
import edu.wpi.first.wpilibj.VictorSP;

import edu.wpi.first.wpilibj.command.PIDSubsystem;
import edu.wpi.first.wpilibj.livewindow.LiveWindow;

/**
 *
 */
public class PIDVisionDrivetrain extends PIDSubsystem {

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTANTS

    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS
    private final AnalogPotentiometer fakeAnalogPotentiometer1 = RobotMap.pIDVisionDrivetrainFakeAnalogPotentiometer1;
    private final SpeedController fakeMotor = RobotMap.pIDVisionDrivetrainFakeMotor;

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DECLARATIONS

    // Initialize your subsystem here
    public PIDVisionDrivetrain() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        super("PIDVisionDrivetrain", -0.85, -0.0105, -0.03);
        setAbsoluteTolerance(0.02);
        getPIDController().setContinuous(false);
        LiveWindow.addActuator("PID Vision Drivetrain", "PIDSubsystem Controller", getPIDController());

    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=PID
        
        //init the local pointer to the PID controller...
        m_PIDctl = getPIDController();

        // Use these to get going:
        // setSetpoint() -  Sets where the PID controller should move the system
        //                  to
        // enable() - Enables the PID controller.
    }

    public void initDefaultCommand() {
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND


    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=DEFAULT_COMMAND

        // Set the default command for a subsystem here.
        //setDefaultCommand(new MySpecialCommand());
    }

    protected double returnPIDInput() {
        // Return your input value for the PID loop
        // e.g. a sensor, like a potentiometer:
        // yourPot.getAverageVoltage() / kYourMaxVoltage;

        // !BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
        //return fakeAnalogPotentiometer1.get();

        // !END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=SOURCE
    	
    	// Get the vision target centered X position from networkTables
    	
    	double xPos = Robot.vision.getScaledTargetXpos();
    	//System.out.println("PID Input says" + xPos);
    	return xPos;
        
    }

    protected void usePIDOutput(double output) {
        // Use output to drive your system, like a motor
        // e.g. yourMotor.set(output);

        // !BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
        //leftMotor.pidWrite(output);

        // !END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=OUTPUT
    	
    	// set the output
    	//System.out.println("TankDrive would have run with output = " + output);
    	// Since motors don't like to output very small values, we have a real issue with being "very close" to the setpoint.
    	// Tuning "I" doesn't help because we reach the nonlinear part of the motor curve and then overshoot massively.
    	// Therefore, try an experiment to set a "minimum" value that we will clammp to and force some reasonable motor outputs...
    	System.out.println("Trying to center by driving at " + output);
    	double outputMin = 0.375;
    	if ((Math.abs(output) > 0) &&
    		(Math.abs(output) < outputMin))  // if between 0 and +/-0.3 (but let zero really shut off the motor)
    	{
    		if (output < 0)
    			output = -outputMin;
    		else
    			output = outputMin;
    	}
    	    	
    	// Note:  We could also just drive one side of the robot to avoid the confusion of the differential.
    	
    	//Based on the current error, we may need to change the PID values for the next iteration.
    	// Algo:
    	// For large errors, let the P term dominate, and don't restrict any of the other terms.
    	// For small-ish errors, we increase the P but begin to limit the max output.  this effectively
    	//     increases the P power to overcome the motor resistance to startup, but the output clamp
    	//     prevents us from going too fast and over-shooting the setpoint
    	// For very small errors, really crank up the P to force the motor to activate, but again limit
    	//     the output (to an even smaller value) so we are guaranteed to move, but not overshoot.
    	// Thus, the implementation will look something like this (actual values subject to change/tweak)
    	// if error angle is x > 5 degrees, use original PID = -0.85, -0.0105, -0.03 and output_max = 1
    	// if error angle is 1 < x < 5, use P = -4, and output_max = 0.375
    	// if error angle is x < 1, use P=-10, and output_max = 0.2
    	
    	double angleError = Robot.vision.getTargetOffsetDegrees();
    	double newP, outputMax;
    	if (angleError >= 5) {
    		newP = -0.85;
    		outputMax = 1.0;
    	}
    	else if (angleError >= 1) {
    		newP = -4;
    		outputMax = 0.375;
    	}
    	else {
    		newP = -10;
    		outputMax = 0.2;
    	}
    	
    	//Set the new P and outputMax values
    	//m_PIDctl.setPID(newP, m_PIDctl.getI(), m_PIDctl.getD());
    	if ((Math.abs(output) > 0) &&
        		(Math.abs(output) > outputMax))  // if between 0 and +/-0.3 (but let zero really shut off the motor)
        	{
        		if (output < 0) {
        			//output = -outputMax;
        		}
        		else {
        			//output = outputMax;
        		}
        	}
    	
    	System.out.println("Final value is " + output);
    	Robot.driveTrain.tankDrive(output, -output);

    }
    
    //Keep the controller as a local variable to save function call overhead
    PIDController m_PIDctl;
    double outputMax = 1.0; //max value to limit motor output

}
